- package-lock.json
- package.json
- src/App.tsx
- src/index.tsx
- src/pages/HomePage.tsx
- src/pages/LoginPage.tsx
- src/pages/RegisterPage.tsx
- Used `npm install react-router-dom`
- Added three pages using the router: /home, /login, /register
- The default page "/" is the same as the register page "/register" for now.
- Verified that registration still works by registering and checking the Firebase authentication list.
> added react router and organized into pages

- package-lock.json
- package.json
- src/App.tsx
- src/pages/AboutPage.tsx
it looks okay, still needs some updating to the style (to match the figma), but the basic layout is implemented
> about-page

- public/index.html
- src/App.css
- src/App.tsx
- src/pages/LearnPage.tsx
- Followed the Figma design to create an initial draft of the learn page at "/learn"
- Imported the "Raleway" font
- Changed the html page title from "React App" to "O(fast)"
Figma:
https://github.com/ofast-team/ofast/assets/46213673/20323f8d-3ecf-4106-b88c-58e7aa6e5388
> First draft of the learn page

- firebase.json
- functions/firebase-debug.log
- functions/package-lock.json
- functions/package.json
- functions/src/index.ts
- package-lock.json
- package.json
Set up express and created a hello world to test basic API calls.
> Set up functions file

- src/App.tsx
- src/components/InlineSpacing.tsx
- src/components/ProblemsTable.tsx
- src/components/SearchBar.tsx
- src/pages/LearnPage.tsx
- src/pages/RegisterPage.tsx
- src/pages/SolvePage.tsx
- Created the solve page
- The table is filled with placeholder data
- Reused the search bar from the learn page
- Reorganized some components into their own files
https://github.com/ofast-team/ofast/assets/46213673/8fd80311-c5a5-4a2a-81e5-c32eb52ad0f3
> Create solve page

- functions/src/index.ts
> Removed "/*" from origins

- .vscode/settings.json
- src/components/MCQBlock.tsx
- src/pages/LearnPage.tsx
- src/pages/LessonPage.tsx
MCQ Block implemented and designed:
- checkbox if multiple answers
- radio if only one answer
- dialog pop up for correct, incorrect, and show answers
- sample question shown
- in lessonpage, added back button
> OFAST-52 MCQBlock

- src/App.tsx
- src/pages/NavBar.tsx
- deleted the unused code
- updated redirecting (anything else besides declared) to home page
- responsive navbar updated to also display "Get Started" button
> fixed navbar unused

- src/components/FITBBlock.tsx
- src/components/MCQBlock.tsx
- src/pages/LearnPage.tsx
This is a super rough draft, but this code is worth pushing because it adds value and doesn't break anything.
You can access the component after the formulas on the Brute Force lesson page
Things I will implement for future PRs
1. Implementing multiple blanks
2. Flexibility for width of the blanks
3. Providing feedback to user for incorrect answers
4. Flexibility for answers that differ due to white-space or differ by 1 character
5. Ability to use markdown code (maybe by nesting reading block??)
> Fill in the Blank ROUGH DRAFT

- src/pages/LoginPage.tsx
> Change helloWorld GET to POST

- .github/workflows/make.yml
- package-lock.json
- package.json
- src/functions/FetchLessonContent.ts
- src/functions/FileFetcher.ts
- src/functions/__tests__/FileFetcher.test.ts
- src/pages/LearnPage.tsx
- refactor to pull the markdown content from the content repo
- added method to fetch files
- added jest for the fetch method
- set up the CI to run tests
> pull markdown content from content repo

- src/functions/FetchLessonContent.ts
- src/functions/FileFetcher.ts
- src/react-app-env.d.ts
- src/setupTests.ts
- removed files that I don't think we actually care about
- added docs for the file fetching methods
> small cleanups and add documentation for file fetching methods

- src/components/NavBar.tsx
- src/pages/LearnPage.tsx
- Changed to profile icon
- Added ```submit``` to navbar
- Added keys to learn page
> Logged In Navbar

- package-lock.json
- package.json
- src/components/ClickOutside.tsx
- src/components/ProblemBody.tsx
- src/components/ProblemsTable.tsx
- src/components/SearchBar.tsx
- src/pages/MockProblemData.tsx
- src/pages/ProblemPage.tsx
- src/pages/SolvePage.css
- src/pages/SolvePage.tsx
These updates are for the Solve Page. Added problem search feature and now fetching problems from MockProblemData.
- Typing into the search bar searches the mock problem archive using the problem title shows a list of search results. The problem can be clicked on to go to the problem page.
- Installed framer-motion for some subtle animation on the search result items. We will likely also use this library to improve other parts of the website.
- Before, the problems in the problem table were sourced from its own list of mock problem data. Now, the problems are fetched from the same source as the problem page content, which is MockProblemData.tsx. This file contains the mock problem data, as well as functions for retrieving problem data. If we move problem fetching to the backend, these …
> OFAST-100 Search and Fetch Problems

- src/App.css
- src/App.tsx
- src/components/NavBar.tsx
- src/components/ProblemBody.tsx
- src/pages/LessonPage.css
**- TRY ON WINDOWS TO CHECK IF TOO THIN!!!!!**
- Changed font to Roboto, only using font weight of 300, 500, 700
- Removed textTransform for all buttons (no caps)
- All headings are font weight 500
- Paragraph text set to 300 to have clear emphasize on formulas/equations
> Font adjust

- public/lessons/dynamic_programming/Fitb2.mdx
- public/lessons/dynamic_programming/Mcq1.mdx
- public/lessons/dynamic_programming/Mcq2.mdx
- src/lessons.json
Added a hint and answer explanation the the first multiple choice question:
Added a FITB question about the definition of memoization and tabulation:
Added another multiple choice question to demonstrate the select all that apply style:
> Added extra questions to D.P. lesson to fully demonstrate the blocks

- src/components/MDXRenderer.tsx
- anchor link auto scrolling was not working for an optimized build
- added a 300ms delay before anchor link scrolling and tested that this works on an optimized build
- could not find a way to do this without a delay
https://github.com/ofast-team/frontend/assets/46213673/1f715720-2b18-4bed-aa0e-f457562fe056
> Fix Anchor Link Auto Scrolling

- public/index.html
- Changed from "Web site created using create-react-app" to "Learn and Solve for Competitive Programming"
> Changed meta content

- src/App.tsx
- src/components/VerificationBanner.tsx
- src/pages/LoginPage.tsx
- src/pages/RegisterPage.tsx
- src/pages/RestrictedPage.tsx
- src/pages/SubmitPage.tsx
- src/userSlice.ts
Short demonstration and explanation of what it's doing.
https://youtu.be/n5LiF1X7gj0
I am now storing on react-redux ("on the browser") whether or not the user is verified, so we're good to go to start restricted access where we need to. Whenever the user refreshes the page, I call an API endpoint that checks the user's verification status.
I created a page called RestrictedPage.tsx that displays a message when users try to access a feature that requires email verification. We can improve the UI if time permits.
> Email Verification Banner, and Login/Reg. Feedback

- src/pages/SubmitPage.tsx
Submissions are now working. Let's merge this quickly, thanks!
> Fix submit() 500 Error

- src/components/ProblemPage/ProblemBlockCards.tsx
- src/pages/SubmissionsList.tsx
- src/pages/VerdictPage.tsx
- Connected SubmissionsList to getSubmissions API
- URL takes in the problem id.
- Added buttons to view the individual submissions in the table
- Problem Name links user back to the problem
- Quite a bit of refactoring within the two files.
There is still a little bit of flickering when switching pages that is bothering me. I wrote some logic to not render the UI until the fetch has completed, but it hasn't completely worked. I could use some help with this next week, but I think I should move on for now. Let's get code upload and problem submission working first!
https://github.com/ofast-team/frontend/assets/51721851/8257a52e-ff1d-48f5-8bc6-bb897f9c1e47
> Connect submissions page

- src/components/ProblemPage/ProblemBlockCards.tsx
- submit from problems page
- default design for input file
https://github.com/ofast-team/frontend/assets/84353905/c2bc2036-9e10-4504-84b2-cd1a49235745
- need to work on the css, style centered and match our palette.
> Problems submit

- src/pages/VerdictPage.tsx
> Make the icons wrap.

- src/components/ProblemPage/ProblemBlockCards.tsx
|before|after|
|-|-|
|![image](https://github.com/ofast-team/frontend/assets/46213673/d94461a8-f772-4128-bc84-434976cf31a6)|![image](https://github.com/ofast-team/frontend/assets/46213673/c685f0af-e334-41f3-8f15-b687b4f45ea8)|
|![resources before](https://github.com/ofast-team/frontend/assets/46213673/89e5727a-da3a-47e6-a150-c1b64fffad42)|![image](https://github.com/ofast-team/frontend/assets/46213673/204f499a-e6c8-4ec4-a054-5de00c1c6d8c)|
> OFAST-173 Wrap problem tags and resources

- src/components/ProblemPage/ProblemBlock.tsx
- src/components/ProblemPage/ProblemBlockCards.tsx
- src/components/ProblemPage/ProblemBody.tsx
- fixed copy double new lines
- added horizontal scrolling for long lines
- added copy button
- styling updates
- made whole page more compatible for smaller screen sizes
- extra: centered problem tags and resources
https://github.com/ofast-team/frontend/assets/46213673/0ba9e5d2-4d9b-471f-b1ae-a5bab5ab2b80
> OFAST-174 Problem Sample Data Updates

- src/components/FITBBlank.tsx
- src/components/FITBBlock.tsx
- src/components/Header.tsx
- src/components/MCQBlock.tsx
- src/components/NavBar.tsx
- Removed the Groups button
- Changed the look of the MCQ and FITB slightly to make room for headers.
- Made the submit button 25% larger
- Fixed a bug with FITB where you could get "correct" by opening the fitb and immediately submitting.
- Fixed a bug with MCQ where you could submit no answer.
I added some headers to my lesson just for this video to show how it could look: I tried putting headers at the beginning of each series of questions instead of each question. The decision of where to put the headers will be up to the contributor.
https://github.com/ofast-team/frontend/assets/51721851/8560cc60-3560-40dc-b66c-c3bc16a97736
> Minor UI fixes

- src/components/PieChart.tsx
- src/components/ProfileCard.tsx
- src/components/ProfileProgressCard.tsx
- src/pages/ProfilePage.tsx
- Fetched API data for user's submissions (now updated upon receiving a submission verdict)
- Removed 'edit' and 'remove' buttons from avatar, replaced with user's initials.
- Displaying total submissions and AC ratio with some neat little icons.
- Added some edge cases for when the user hasn't submitted anything yet.
- Initials accommodate a single name (if there are more than 2 words in the name, it'll only display the first two.
A quick video to show some of the edge cases with the initials thing:
https://github.com/ofast-team/frontend/assets/51721851/0d0c45bf-61f5-46b6-afd9-c75efdbd8c61
> Pie chart & more

- public/lessons/dynamic-programming/fitb-1.mdx
- public/lessons/dynamic-programming/fitb-2.mdx
- public/lessons/dynamic-programming/mcq-2.mdx
- public/lessons/dynamic-programming/problem-building.mdx
- public/lessons/dynamic-programming/problem-twosum.mdx
- public/lessons/greedy/coin-change-mcq.mdx
- public/lessons/greedy/exchange-arguments.mdx
- public/lessons/runtime-analysis/mcq-1.mdx
- public/lessons/runtime-analysis/mcq-3.mdx
- public/lessons/runtime-analysis/problem-solving.mdx
- src/lessons.json
Getting the current lessons ready for STEM Day.
-Added 'Quiz' TOC headers for Runtime Analysis
- Added Picasso to Greedy Lesson, got it to render by filling in lessons.json
- Fixed latex issues
- Swapped out Two-Sum for Building Gazebos on DP lesson.
> Lesson Cleanup, TOC Headers, using real problems

- src/lessons.json
Removed the Lessons that don't exist and reordered the categories.
> Organize Learn Page

- src/components/ProblemPage/ProblemBlock.tsx
- src/components/ProblemPage/ProblemNotFound.tsx
- src/pages/ProblemPage.tsx
> update the problem not found text & page

- src/App.tsx
- src/pages/ResetPasswordPage.tsx
- src/pages/VerifyEmailPage.tsx
Tyler is sitting next to me, and can see/test the UI.
> Reset Password UI via ofast.io (WIP)

- src/components/ProblemPage/ProblemBlockCards.tsx
- src/components/SubmitPage/SubmitFolderCard.tsx
- src/pages/SubmitPage.tsx
> Custom submit
